
import CoffeeMachine.CoffeeMachine;
import CoffeeMachine.Exceptions.OutOfBeansException;
import CoffeeMachine.Exceptions.OutOfGroundCoffeeException;
import CoffeeMachine.Exceptions.OutOfMilkException;
import CoffeeMachine.Exceptions.OutOfWaterException;
import CoffeeMachine.Exceptions.OverFlowBenasException;
import CoffeeMachine.Exceptions.OverFlowMilkException;
import CoffeeMachine.Exceptions.OverFlowWasteException;
import CoffeeMachine.Exceptions.OverFlowWaterException;
import CoffeeMachine.FileLogger;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
//import CoffeeMachine.OutOfWaterException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class App extends javax.swing.JFrame {

    FileLogger logger = new FileLogger();
    private static DecimalFormat df = new DecimalFormat("#.##");
    ArrayList<String> drinkList = new ArrayList<>();

    CoffeeMachine machine = new CoffeeMachine(logger);
    String coffeeType, coffeeSize, grindSize, beansType;
    int ArabicaBeansToGrind, ArabicaBeansToAdd, RobustaBeansToGrind, RobustaBeansToAdd, waterToAdd, milkToAdd, arabica, robusta;

    /**
     * Creates new form CoffeeMachineJFrame
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEspressoRadio = new javax.swing.JRadioButton();
        jAmericanoRadio = new javax.swing.JRadioButton();
        jLatteRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jDoubleShotRadio = new javax.swing.JRadioButton();
        jSingleShotRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSoftRadio = new javax.swing.JRadioButton();
        jRoughRadio = new javax.swing.JRadioButton();
        jMediumRadio = new javax.swing.JRadioButton();
        jMakeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jArabicaBeansField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jArabicaGroundBeansField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jWaterField = new javax.swing.JTextField();
        jMilkField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRobustaBeansField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRobustaGroundBeansField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jAddArabicaBeansField = new javax.swing.JTextField();
        jAddArabicaBeansButton = new javax.swing.JButton();
        jGrindArabicaBeansButton = new javax.swing.JButton();
        jGrindArabicaField = new javax.swing.JTextField();
        jAddWaterField = new javax.swing.JTextField();
        jAddWaterButton = new javax.swing.JButton();
        jAddMilkButton = new javax.swing.JButton();
        jAddMilkField = new javax.swing.JTextField();
        jAddRobustaBeansButton = new javax.swing.JButton();
        jAddRobustaBeansField = new javax.swing.JTextField();
        jGrindRobustaBeansButton = new javax.swing.JButton();
        jGrindRobustaField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jEmptyButton = new javax.swing.JButton();
        jWasteField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jNormalRadio1 = new javax.swing.JRadioButton();
        jArabicaSlider = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRobustaSlider = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHistoryList = new javax.swing.JList<>();
        jDeleteFromHistoryButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Machine");

        jPanel1.setBackground(new java.awt.Color(189, 114, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose your type of coffee:");

        buttonGroup1.add(jEspressoRadio);
        jEspressoRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEspressoRadio.setForeground(new java.awt.Color(255, 255, 255));
        jEspressoRadio.setText("Espresso");
        jEspressoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEspressoRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jAmericanoRadio);
        jAmericanoRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jAmericanoRadio.setForeground(new java.awt.Color(255, 255, 255));
        jAmericanoRadio.setText("Americano");
        jAmericanoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmericanoRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLatteRadio);
        jLatteRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLatteRadio.setForeground(new java.awt.Color(255, 255, 255));
        jLatteRadio.setText("Latte");
        jLatteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLatteRadioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose your size of coffee:");

        buttonGroup2.add(jDoubleShotRadio);
        jDoubleShotRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDoubleShotRadio.setForeground(new java.awt.Color(255, 255, 255));
        jDoubleShotRadio.setText("Double shot");
        jDoubleShotRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoubleShotRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(jSingleShotRadio);
        jSingleShotRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSingleShotRadio.setForeground(new java.awt.Color(255, 255, 255));
        jSingleShotRadio.setText("Single shot");
        jSingleShotRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSingleShotRadioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose the grind size of the coffee beans:");

        buttonGroup3.add(jSoftRadio);
        jSoftRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSoftRadio.setForeground(new java.awt.Color(255, 255, 255));
        jSoftRadio.setText("Soft");
        jSoftRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoftRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRoughRadio);
        jRoughRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRoughRadio.setForeground(new java.awt.Color(255, 255, 255));
        jRoughRadio.setText("Rough");
        jRoughRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoughRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(jMediumRadio);
        jMediumRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMediumRadio.setForeground(new java.awt.Color(255, 255, 255));
        jMediumRadio.setText("Medium");
        jMediumRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMediumRadioActionPerformed(evt);
            }
        });

        jMakeButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        jMakeButton.setText("Make your cup");
        jMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMakeButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(228, 188, 132));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machine Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Arabica Beans: (gram)");

        jArabicaBeansField.setEditable(false);
        jArabicaBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jArabicaBeansField.setText("100");
        jArabicaBeansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArabicaBeansFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Arabica Ground Beans: (gram)");

        jArabicaGroundBeansField.setEditable(false);
        jArabicaGroundBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jArabicaGroundBeansField.setText("0");
        jArabicaGroundBeansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArabicaGroundBeansFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Water Tank: (ml)");

        jWaterField.setEditable(false);
        jWaterField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jWaterField.setText("1000");
        jWaterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWaterFieldActionPerformed(evt);
            }
        });

        jMilkField.setEditable(false);
        jMilkField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMilkField.setText("800");
        jMilkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMilkFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Milk Tank: (ml)");

        jLabel8.setText("Max: 100g");

        jLabel9.setText("Max: 1000ml");

        jLabel10.setText("Max: 800ml");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Robusta Beans: (gram)");

        jRobustaBeansField.setEditable(false);
        jRobustaBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRobustaBeansField.setText("100");
        jRobustaBeansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRobustaBeansFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Max: 100g");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Robusta Ground Beans: (gram)");

        jRobustaGroundBeansField.setEditable(false);
        jRobustaGroundBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRobustaGroundBeansField.setText("0");
        jRobustaGroundBeansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRobustaGroundBeansFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jArabicaBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(jRobustaBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWaterField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(jArabicaGroundBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(35, 35, 35)
                        .addComponent(jRobustaGroundBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jArabicaBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRobustaBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jArabicaGroundBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRobustaGroundBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWaterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(228, 188, 132));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machine Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jAddArabicaBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jAddArabicaBeansButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddArabicaBeansButton.setText("Add Arabica Beans");
        jAddArabicaBeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddArabicaBeansButtonActionPerformed(evt);
            }
        });

        jGrindArabicaBeansButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jGrindArabicaBeansButton.setText("Grind Arabica beans");
        jGrindArabicaBeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrindArabicaBeansButtonActionPerformed(evt);
            }
        });

        jGrindArabicaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGrindArabicaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrindArabicaFieldActionPerformed(evt);
            }
        });

        jAddWaterField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAddWaterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWaterFieldActionPerformed(evt);
            }
        });

        jAddWaterButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddWaterButton.setText("Add Water ");
        jAddWaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWaterButtonActionPerformed(evt);
            }
        });

        jAddMilkButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddMilkButton.setText("Add Milk");
        jAddMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddMilkButtonActionPerformed(evt);
            }
        });

        jAddMilkField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jAddRobustaBeansButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddRobustaBeansButton.setText("Add Robusta Beans");
        jAddRobustaBeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddRobustaBeansButtonActionPerformed(evt);
            }
        });

        jAddRobustaBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jGrindRobustaBeansButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jGrindRobustaBeansButton.setText("Grind Robusta beans");
        jGrindRobustaBeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrindRobustaBeansButtonActionPerformed(evt);
            }
        });

        jGrindRobustaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGrindRobustaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrindRobustaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jAddRobustaBeansButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jAddMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAddMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jGrindRobustaBeansButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jGrindArabicaBeansButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jAddWaterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jAddArabicaBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jGrindArabicaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jAddWaterField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jAddArabicaBeansField))
                                    .addComponent(jGrindRobustaField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAddRobustaBeansField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddArabicaBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddArabicaBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddRobustaBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddRobustaBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGrindArabicaBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGrindArabicaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGrindRobustaBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGrindRobustaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddWaterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddWaterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jEmptyButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmptyButton.setText("Empty the waste field");
        jEmptyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmptyButtonActionPerformed(evt);
            }
        });

        jWasteField.setEditable(false);
        jWasteField.setText("20");
        jWasteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWasteFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Choose the type of the coffee beans:");

        jNormalRadio1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jNormalRadio1.setForeground(new java.awt.Color(255, 255, 255));
        jNormalRadio1.setText("Normal");
        jNormalRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNormalRadio1ActionPerformed(evt);
            }
        });

        jArabicaSlider.setForeground(new java.awt.Color(255, 255, 255));
        jArabicaSlider.setMajorTickSpacing(10);
        jArabicaSlider.setMinorTickSpacing(10);
        jArabicaSlider.setPaintLabels(true);
        jArabicaSlider.setPaintTicks(true);
        jArabicaSlider.setSnapToTicks(true);
        jArabicaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jArabicaSliderStateChanged(evt);
            }
        });
        jArabicaSlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jArabicaSliderPropertyChange(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Arabica:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Robusta:");

        jRobustaSlider.setMajorTickSpacing(10);
        jRobustaSlider.setMinorTickSpacing(10);
        jRobustaSlider.setPaintLabels(true);
        jRobustaSlider.setPaintTicks(true);
        jRobustaSlider.setSnapToTicks(true);
        jRobustaSlider.setEnabled(false);
        jRobustaSlider.setFocusCycleRoot(true);
        jRobustaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRobustaSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(619, 619, 619)
                                .addComponent(jEmptyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jWasteField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSingleShotRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(jDoubleShotRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jEspressoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jAmericanoRadio)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLatteRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSoftRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jRoughRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jMediumRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jNormalRadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jArabicaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRobustaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRobustaSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(3, 3, 3)))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNormalRadio1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jArabicaSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEspressoRadio)
                        .addComponent(jAmericanoRadio))
                    .addComponent(jLatteRadio))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSingleShotRadio)
                    .addComponent(jDoubleShotRadio))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSoftRadio)
                            .addComponent(jRoughRadio)
                            .addComponent(jMediumRadio))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmptyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWasteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(308, 308, 308))
        );

        jTabbedPane1.addTab("Main", jPanel1);

        jHistoryList.setBorder(javax.swing.BorderFactory.createTitledBorder("Your history"));
        jHistoryList.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jHistoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jHistoryListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jHistoryList);

        jDeleteFromHistoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDeleteFromHistoryButton.setText("Delete from history");
        jDeleteFromHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteFromHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDeleteFromHistoryButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jDeleteFromHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("History", jPanel2);

        jMenu1.setText("File");

        jMenuItem1.setText("Save");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Close");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDoubleShotRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoubleShotRadioActionPerformed
        // TODO add your handling code here:
        coffeeSize = evt.getActionCommand().toLowerCase();
    }//GEN-LAST:event_jDoubleShotRadioActionPerformed

//    void display() {
//        String[] arr = new String[drinkList.size()];
//        for (int i = 0; i < drinkList.size(); i++) {
//            arr[i] = drinkList.get(i);
//        }
//        jHistoryList.setListData(arr);
//    }
    void Display() {
        try (FileReader fileReader = new FileReader("machine.log"); BufferedReader bufferedReader = new BufferedReader(fileReader)) {
            String line;
            drinkList.clear();
            while ((line = bufferedReader.readLine()) != null) {
                drinkList.add(line);
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
        String[] arr = new String[drinkList.size()];
        for (int i = 0; i < drinkList.size(); i++) {
            arr[i] = drinkList.get(i);
        }
        jHistoryList.setListData(arr);
    }

    private void jMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMakeButtonActionPerformed
        // TODO add your handling code here:
        if (grindSize != null && coffeeType != null && coffeeSize != null) {
            if ("Latte".equals(coffeeType)) {
                try {
                    machine.newLatteCoffee(arabica, coffeeType, coffeeSize, grindSize);
                    jArabicaGroundBeansFieldActionPerformed(evt);
                    jArabicaBeansFieldActionPerformed(evt);
                    jRobustaGroundBeansFieldActionPerformed(evt);
                    jRobustaBeansFieldActionPerformed(evt);
                    jWaterFieldActionPerformed(evt);
                    jMilkFieldActionPerformed(evt);
                    jWasteFieldActionPerformed(evt);
//                    String drink = "Coffee Type: " + coffeeType + "         Coffee Size: " + coffeeSize + "          Grind Size: " + grindSize;
                    drinkList.add(machine.GetCoffeeInformation());
//                    display();
                    Display();
                    JOptionPane.showMessageDialog(rootPane, machine.GetCoffeeInformation());
                } catch (OverFlowWasteException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } catch (OutOfGroundCoffeeException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } catch (OutOfMilkException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                return;
            }
            try {
                machine.newCoffeeCup(arabica, coffeeType, coffeeSize, grindSize);
                jArabicaGroundBeansFieldActionPerformed(evt);
                jArabicaBeansFieldActionPerformed(evt);
                jRobustaGroundBeansFieldActionPerformed(evt);
                jRobustaBeansFieldActionPerformed(evt);
                jWaterFieldActionPerformed(evt);
                jMilkFieldActionPerformed(evt);
                jWasteFieldActionPerformed(evt);
//                String drink = "Coffee Type: " + coffeeType + "         Coffee Size: " + coffeeSize + "          grind Size: " + grindSize;
                drinkList.add(machine.GetCoffeeInformation());
//                display();
                Display();
                JOptionPane.showMessageDialog(rootPane, machine.GetCoffeeInformation());
            } catch (OutOfWaterException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(machine.GetWaterCapacity()));
            } catch (OverFlowWasteException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch (OutOfGroundCoffeeException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Some information is missing");
        }
    }//GEN-LAST:event_jMakeButtonActionPerformed

    private void jEspressoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEspressoRadioActionPerformed
        // TODO add your handling code here:
        coffeeType = evt.getActionCommand();
        jSingleShotRadio.setVisible(true);
    }//GEN-LAST:event_jEspressoRadioActionPerformed

    private void jAmericanoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmericanoRadioActionPerformed
        // TODO add your handling code here:
        coffeeType = evt.getActionCommand();
        jSingleShotRadio.setVisible(true);
    }//GEN-LAST:event_jAmericanoRadioActionPerformed

    private void jLatteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLatteRadioActionPerformed
        // TODO add your handling code here:
        coffeeType = evt.getActionCommand();
        jDoubleShotRadio.setSelected(true);
        jSingleShotRadio.setVisible(false);
        coffeeSize = "double shot";
    }//GEN-LAST:event_jLatteRadioActionPerformed

    private void jSingleShotRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSingleShotRadioActionPerformed
        // TODO add your handling code here:
        coffeeSize = evt.getActionCommand().toLowerCase();
    }//GEN-LAST:event_jSingleShotRadioActionPerformed

    private void jSoftRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoftRadioActionPerformed
        // TODO add your handling code here:
        grindSize = evt.getActionCommand();
    }//GEN-LAST:event_jSoftRadioActionPerformed

    private void jRoughRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoughRadioActionPerformed
        // TODO add your handling code here:
        grindSize = evt.getActionCommand();
    }//GEN-LAST:event_jRoughRadioActionPerformed

    private void jMediumRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMediumRadioActionPerformed
        // TODO add your handling code here:
        grindSize = evt.getActionCommand();
    }//GEN-LAST:event_jMediumRadioActionPerformed

    private void jArabicaBeansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArabicaBeansFieldActionPerformed
        // TODO add your handling code here:
        int ArabicaBeansCapacity = machine.GetArabicaBeansCapacity();
        jArabicaBeansField.setText(ArabicaBeansCapacity + "");
    }//GEN-LAST:event_jArabicaBeansFieldActionPerformed

    private void jArabicaGroundBeansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArabicaGroundBeansFieldActionPerformed
        // TODO add your handling code here:
        double ArabicagroundBeans = machine.GetArabicaGroundPowder();
        String formated = df.format(ArabicagroundBeans);
        jArabicaGroundBeansField.setText(formated + "");
    }//GEN-LAST:event_jArabicaGroundBeansFieldActionPerformed

    private void jWaterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWaterFieldActionPerformed
        // TODO add your handling code here:
        int WaterCapcity = machine.GetWaterCapacity();
        jWaterField.setText(WaterCapcity + "");
    }//GEN-LAST:event_jWaterFieldActionPerformed

    private void jGrindArabicaBeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrindArabicaBeansButtonActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(jGrindArabicaField.getText())) {
                JOptionPane.showMessageDialog(null, "You have to enter a number value");
                return;
            }
            ArabicaBeansToGrind = Integer.parseInt(jGrindArabicaField.getText());
            if (ArabicaBeansToGrind < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jGrindArabicaField.setText("");
                return;
            }
            machine.grindArabicaCoffee(ArabicaBeansToGrind);
            jArabicaBeansFieldActionPerformed(evt);
            jArabicaGroundBeansFieldActionPerformed(evt);
            jGrindArabicaField.setText("");
            Display();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jGrindArabicaField.setText("");
        } catch (OutOfBeansException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jGrindArabicaField.setText("");
        }
    }//GEN-LAST:event_jGrindArabicaBeansButtonActionPerformed

    private void jAddArabicaBeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddArabicaBeansButtonActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(jAddArabicaBeansField.getText())) {
                JOptionPane.showMessageDialog(null, "You have to enter a number value");
                return;
            }
            ArabicaBeansToAdd = Integer.parseInt(jAddArabicaBeansField.getText());
            if (ArabicaBeansToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddArabicaBeansField.setText("");
                return;
            }
            machine.SetArabicaBeansCapacity(ArabicaBeansToAdd);
            jArabicaBeansFieldActionPerformed(evt);
            jAddArabicaBeansField.setText("");
            Display();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddArabicaBeansField.setText("");
        } catch (OverFlowBenasException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddArabicaBeansField.setText("");
        }
    }//GEN-LAST:event_jAddArabicaBeansButtonActionPerformed

    private void jGrindArabicaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrindArabicaFieldActionPerformed
        // TODO add your handling code here:;
    }//GEN-LAST:event_jGrindArabicaFieldActionPerformed

    private void jMilkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMilkFieldActionPerformed
        // TODO add your handling code here:
        int milkCapcity = machine.GetMilkCapacity();
        jMilkField.setText(milkCapcity + "");
    }//GEN-LAST:event_jMilkFieldActionPerformed

    private void jAddWaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWaterButtonActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(jAddWaterField.getText())) {
                JOptionPane.showMessageDialog(null, "You have to enter a number value");
                return;
            }
            waterToAdd = Integer.parseInt(jAddWaterField.getText());
            if (waterToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddWaterField.setText("");
                return;
            }
            machine.SetWaterCapacity(waterToAdd);
            jWaterFieldActionPerformed(evt);
            jAddWaterField.setText("");
            Display();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddWaterField.setText("");
        } catch (OverFlowWaterException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddWaterField.setText("");
        } catch (HeadlessException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jAddWaterButtonActionPerformed

    private void jAddMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddMilkButtonActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(jAddMilkField.getText())) {
                JOptionPane.showMessageDialog(null, "You have to enter a number value");
                return;
            }
            milkToAdd = Integer.parseInt(jAddMilkField.getText());
            if (milkToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddMilkField.setText("");
                return;
            }
            machine.SetMilkCapacity(milkToAdd);
            jMilkFieldActionPerformed(evt);
            jAddMilkField.setText("");
            Display();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddMilkField.setText("");
        } catch (OverFlowMilkException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddMilkField.setText("");
        }
    }//GEN-LAST:event_jAddMilkButtonActionPerformed

    private void jAddWaterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWaterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddWaterFieldActionPerformed

    private void jDeleteFromHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteFromHistoryButtonActionPerformed
        // TODO add your handling code here:
        int index = jHistoryList.getSelectedIndex();
        if (index != -1) {
            drinkList.remove(index);
//            display();
        Display();
        }
    }//GEN-LAST:event_jDeleteFromHistoryButtonActionPerformed

    private void jHistoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jHistoryListValueChanged
        // TODO add your handling code here:
        int index = jHistoryList.getSelectedIndex();
        if (index != -1) {
            JOptionPane.showMessageDialog(rootPane, drinkList.get(index));
        }
    }//GEN-LAST:event_jHistoryListValueChanged

    private void jWasteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWasteFieldActionPerformed
        // TODO add your handling code here:
        int wasteCapacity = machine.GetWasteCapacity();
        jWasteField.setText(wasteCapacity + "");
    }//GEN-LAST:event_jWasteFieldActionPerformed

    private void jEmptyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmptyButtonActionPerformed
        // TODO add your handling code here:
        machine.SetWaste(20);
        jWasteFieldActionPerformed(evt);
        Display();
    }//GEN-LAST:event_jEmptyButtonActionPerformed

    private void jNormalRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNormalRadio1ActionPerformed
        // TODjArabicaBeansFieldhandling code here:
        beansType = jNormalRadio1.getActionCommand();
        if (beansType.equals("Normal")) {
            jArabicaSlider.setValue(30);
            jRobustaSlider.setValue((100 - arabica));
        }
        if (jNormalRadio1.isSelected() == false) {
            beansType = "";
        }
    }//GEN-LAST:event_jNormalRadio1ActionPerformed

    private void jArabicaSliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jArabicaSliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jArabicaSliderPropertyChange

    private void jArabicaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jArabicaSliderStateChanged
        arabica = jArabicaSlider.getValue();
        jRobustaSlider.setValue((100 - arabica));
        if (arabica == 30) {
            jNormalRadio1.setFocusPainted(true);
            jNormalRadio1.setSelected(true);
        } else if ("Normal".equals(beansType)) {
            jNormalRadio1.setFocusPainted(true);
            jArabicaSlider.setValue(30);
        } else {
            jNormalRadio1.setSelected(false);
        }
    }//GEN-LAST:event_jArabicaSliderStateChanged

    private void jRobustaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRobustaSliderStateChanged
        robusta = jRobustaSlider.getValue();
    }//GEN-LAST:event_jRobustaSliderStateChanged

    private void jRobustaBeansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRobustaBeansFieldActionPerformed
        // TODO add your handling code here:
        int RobustaBeansCapacity = machine.GetRobustaBeansCapacity();
        jRobustaBeansField.setText(RobustaBeansCapacity + "");
    }//GEN-LAST:event_jRobustaBeansFieldActionPerformed

    private void jRobustaGroundBeansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRobustaGroundBeansFieldActionPerformed
        // TODO add your handling code here:
        double RobustaGroundBeans = machine.GetRobustaGroundPowder();
        String formated = df.format(RobustaGroundBeans);
        jRobustaGroundBeansField.setText(formated + "");
    }//GEN-LAST:event_jRobustaGroundBeansFieldActionPerformed

    private void jAddRobustaBeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddRobustaBeansButtonActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(jAddRobustaBeansField.getText())) {
                JOptionPane.showMessageDialog(null, "You have to enter a number value");
                return;
            }
            RobustaBeansToAdd = Integer.parseInt(jAddRobustaBeansField.getText());
            if (RobustaBeansToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddRobustaBeansField.setText("");
                return;
            }
            machine.SetRobustaBeansCapacity(RobustaBeansToAdd);
            jRobustaBeansFieldActionPerformed(evt);
            jAddRobustaBeansField.setText("");
            Display();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddRobustaBeansField.setText("");
        } catch (OverFlowBenasException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddRobustaBeansField.setText("");
        }
    }//GEN-LAST:event_jAddRobustaBeansButtonActionPerformed

    private void jGrindRobustaBeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrindRobustaBeansButtonActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(jGrindRobustaField.getText())) {
                JOptionPane.showMessageDialog(null, "You have to enter a number value");
                return;
            }
            RobustaBeansToGrind = Integer.parseInt(jGrindRobustaField.getText());
            if (RobustaBeansToGrind < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jGrindRobustaField.setText("");
                return;
            }
            machine.grindRobustaCoffee(RobustaBeansToGrind);
            jRobustaBeansFieldActionPerformed(evt);
            jRobustaGroundBeansFieldActionPerformed(evt);
            jGrindRobustaField.setText("");
            Display();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jGrindRobustaField.setText("");
        } catch (OutOfBeansException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jGrindRobustaField.setText("");
        }
    }//GEN-LAST:event_jGrindRobustaBeansButtonActionPerformed

    private void jGrindRobustaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrindRobustaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGrindRobustaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jAddArabicaBeansButton;
    private javax.swing.JTextField jAddArabicaBeansField;
    private javax.swing.JButton jAddMilkButton;
    private javax.swing.JTextField jAddMilkField;
    private javax.swing.JButton jAddRobustaBeansButton;
    private javax.swing.JTextField jAddRobustaBeansField;
    private javax.swing.JButton jAddWaterButton;
    private javax.swing.JTextField jAddWaterField;
    private javax.swing.JRadioButton jAmericanoRadio;
    private javax.swing.JTextField jArabicaBeansField;
    private javax.swing.JTextField jArabicaGroundBeansField;
    private javax.swing.JSlider jArabicaSlider;
    private javax.swing.JButton jDeleteFromHistoryButton;
    private javax.swing.JRadioButton jDoubleShotRadio;
    private javax.swing.JButton jEmptyButton;
    private javax.swing.JRadioButton jEspressoRadio;
    private javax.swing.JButton jGrindArabicaBeansButton;
    private javax.swing.JTextField jGrindArabicaField;
    private javax.swing.JButton jGrindRobustaBeansButton;
    private javax.swing.JTextField jGrindRobustaField;
    private javax.swing.JList<String> jHistoryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLatteRadio;
    private javax.swing.JButton jMakeButton;
    private javax.swing.JRadioButton jMediumRadio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jMilkField;
    private javax.swing.JRadioButton jNormalRadio1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jRobustaBeansField;
    private javax.swing.JTextField jRobustaGroundBeansField;
    private javax.swing.JSlider jRobustaSlider;
    private javax.swing.JRadioButton jRoughRadio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jSingleShotRadio;
    private javax.swing.JRadioButton jSoftRadio;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jWasteField;
    private javax.swing.JTextField jWaterField;
    // End of variables declaration//GEN-END:variables
}
