
import CoffeeMachine.CoffeeMachine;
import CoffeeMachine.Drink;
import CoffeeMachine.OutOfBeansException;
import CoffeeMachine.OutOfGroundCoffeeException;
import CoffeeMachine.OutOfMilkException;
import CoffeeMachine.OutOfWaterException;
import CoffeeMachine.OverFlowBenasException;
import CoffeeMachine.OverFlowMilkException;
import CoffeeMachine.OverFlowWasteException;
import CoffeeMachine.OverFlowWaterException;
import java.awt.HeadlessException;
//import CoffeeMachine.OutOfWaterException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class App extends javax.swing.JFrame {

    ArrayList<String> drinkList = new ArrayList<>();

    CoffeeMachine machine = new CoffeeMachine();

    String coffeeType, coffeeSize, grindSize;
    int beansToGrind, beansToAdd, waterToAdd, milkToAdd;

    /**
     * Creates new form CoffeeMachineJFrame
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEspressoRadio = new javax.swing.JRadioButton();
        jAmericanoRadio = new javax.swing.JRadioButton();
        jLatteRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jDoubleShotRadio = new javax.swing.JRadioButton();
        jSingleShotRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSoftRadio = new javax.swing.JRadioButton();
        jRoughRadio = new javax.swing.JRadioButton();
        jMediumRadio = new javax.swing.JRadioButton();
        jMakeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBeansField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jGroundBeansField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jWaterField = new javax.swing.JTextField();
        jMilkField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jAddBeansField = new javax.swing.JTextField();
        jAddBeansButton = new javax.swing.JButton();
        jGrindBeansButton = new javax.swing.JButton();
        jGrindField = new javax.swing.JTextField();
        jAddWaterField = new javax.swing.JTextField();
        jAddWaterButton = new javax.swing.JButton();
        jAddMilkButton = new javax.swing.JButton();
        jAddMilkField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jEmptyButton = new javax.swing.JButton();
        jWasteField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHistoryList = new javax.swing.JList<>();
        jDeleteFromHistoryButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Machine");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("Choose your type of coffee:");

        buttonGroup1.add(jEspressoRadio);
        jEspressoRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jEspressoRadio.setText("Espresso");
        jEspressoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEspressoRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jAmericanoRadio);
        jAmericanoRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jAmericanoRadio.setText("Americano");
        jAmericanoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmericanoRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLatteRadio);
        jLatteRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jLatteRadio.setText("Latte");
        jLatteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLatteRadioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("Choose your size of coffee:");

        buttonGroup2.add(jDoubleShotRadio);
        jDoubleShotRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jDoubleShotRadio.setText("Double shot");
        jDoubleShotRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoubleShotRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(jSingleShotRadio);
        jSingleShotRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jSingleShotRadio.setText("Single shot");
        jSingleShotRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSingleShotRadioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel4.setText("Choose the grind size of the coffee beans:");

        buttonGroup3.add(jSoftRadio);
        jSoftRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jSoftRadio.setText("Soft");
        jSoftRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoftRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRoughRadio);
        jRoughRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jRoughRadio.setText("Rough");
        jRoughRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoughRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(jMediumRadio);
        jMediumRadio.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jMediumRadio.setText("Medium");
        jMediumRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMediumRadioActionPerformed(evt);
            }
        });

        jMakeButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        jMakeButton.setText("Make your cup");
        jMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMakeButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(234, 232, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machine Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Beans Container: (gram)");

        jBeansField.setEditable(false);
        jBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBeansField.setText("250");
        jBeansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeansFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ground coffee Beans: (gram)");

        jGroundBeansField.setEditable(false);
        jGroundBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGroundBeansField.setText("0");
        jGroundBeansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGroundBeansFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Water Tank: (ml)");

        jWaterField.setEditable(false);
        jWaterField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jWaterField.setText("1000");
        jWaterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWaterFieldActionPerformed(evt);
            }
        });

        jMilkField.setEditable(false);
        jMilkField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMilkField.setText("800");
        jMilkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMilkFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Milk Tank: (ml)");

        jLabel8.setText("Max: 250g");

        jLabel9.setText("Max: 1000ml");

        jLabel10.setText("Max: 800ml");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(jBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jWaterField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(33, 33, 33)
                            .addComponent(jGroundBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGroundBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWaterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(234, 232, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machine Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jAddBeansField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jAddBeansButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddBeansButton.setText("Add Coffee Beans");
        jAddBeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBeansButtonActionPerformed(evt);
            }
        });

        jGrindBeansButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jGrindBeansButton.setText("Grind coffee beans");
        jGrindBeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrindBeansButtonActionPerformed(evt);
            }
        });

        jGrindField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGrindField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrindFieldActionPerformed(evt);
            }
        });

        jAddWaterField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAddWaterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWaterFieldActionPerformed(evt);
            }
        });

        jAddWaterButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddWaterButton.setText("Add Water ");
        jAddWaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWaterButtonActionPerformed(evt);
            }
        });

        jAddMilkButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jAddMilkButton.setText("Add Milk");
        jAddMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddMilkButtonActionPerformed(evt);
            }
        });

        jAddMilkField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jGrindBeansButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAddWaterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                            .addComponent(jAddMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jAddMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jGrindField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAddWaterField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jAddBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jAddBeansField)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddBeansField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGrindBeansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGrindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddWaterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddWaterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddMilkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jEmptyButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmptyButton.setText("Empty the waste field");
        jEmptyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmptyButtonActionPerformed(evt);
            }
        });

        jWasteField.setEditable(false);
        jWasteField.setText("20");
        jWasteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWasteFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jEspressoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAmericanoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLatteRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSingleShotRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDoubleShotRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jEmptyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jWasteField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSoftRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRoughRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMediumRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEspressoRadio)
                    .addComponent(jAmericanoRadio)
                    .addComponent(jLatteRadio))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSingleShotRadio)
                    .addComponent(jDoubleShotRadio))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSoftRadio)
                    .addComponent(jRoughRadio)
                    .addComponent(jMediumRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmptyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWasteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Main", jPanel1);

        jHistoryList.setBorder(javax.swing.BorderFactory.createTitledBorder("Your history"));
        jHistoryList.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jHistoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jHistoryListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jHistoryList);

        jDeleteFromHistoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDeleteFromHistoryButton.setText("Delete from history");
        jDeleteFromHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteFromHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteFromHistoryButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jDeleteFromHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("History", jPanel2);

        jMenu1.setText("File");

        jMenuItem1.setText("Save");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Close");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDoubleShotRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoubleShotRadioActionPerformed
        // TODO add your handling code here:
        coffeeSize = evt.getActionCommand().toLowerCase();
    }//GEN-LAST:event_jDoubleShotRadioActionPerformed

    void display() {
        String[] arr = new String[drinkList.size()];
        for (int i = 0; i < drinkList.size(); i++) {
            arr[i] = drinkList.get(i);
        }
        jHistoryList.setListData(arr);
    }

    private void jMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMakeButtonActionPerformed
        // TODO add your handling code here:
        if (grindSize != null && coffeeType != null && coffeeSize != null) {
            if ("Latte".equals(coffeeType)) {
                try {
                    machine.newLatteCoffee(coffeeType, coffeeSize, grindSize);
                } catch (OverFlowWasteException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } catch (OutOfGroundCoffeeException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } catch (OutOfMilkException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                jGroundBeansFieldActionPerformed(evt);
                jBeansFieldActionPerformed(evt);
                jWaterFieldActionPerformed(evt);
                jMilkFieldActionPerformed(evt);
                jWasteFieldActionPerformed(evt);
                String drink = "Coffee Type: " + coffeeType + "         Coffee Size: " + coffeeSize + "          grind Size: " + grindSize;
                drinkList.add(drink);
                display();
                return;
            }
            try {
                machine.newCoffeeCup(coffeeType, coffeeSize, grindSize);
            } catch (OutOfWaterException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(machine.GetWaterCapacity()));
            } catch (OverFlowWasteException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch (OutOfGroundCoffeeException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            jGroundBeansFieldActionPerformed(evt);
            jBeansFieldActionPerformed(evt);
            jWaterFieldActionPerformed(evt);
            jMilkFieldActionPerformed(evt);
            jWasteFieldActionPerformed(evt);
            String drink = "Coffee Type: " + coffeeType + "         Coffee Size: " + coffeeSize + "          grind Size: " + grindSize;
            drinkList.add(drink);
            display();

        } else {
            JOptionPane.showMessageDialog(null, "Some information is missing");
        }
    }//GEN-LAST:event_jMakeButtonActionPerformed

    private void jEspressoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEspressoRadioActionPerformed
        // TODO add your handling code here:
        coffeeType = evt.getActionCommand();
        jSingleShotRadio.setVisible(true);
    }//GEN-LAST:event_jEspressoRadioActionPerformed

    private void jAmericanoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmericanoRadioActionPerformed
        // TODO add your handling code here:
        coffeeType = evt.getActionCommand();
        jSingleShotRadio.setVisible(true);
    }//GEN-LAST:event_jAmericanoRadioActionPerformed

    private void jLatteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLatteRadioActionPerformed
        // TODO add your handling code here:
        coffeeType = evt.getActionCommand();
        jDoubleShotRadio.setSelected(true);
        jSingleShotRadio.setVisible(false);
        coffeeSize = "double shot";
    }//GEN-LAST:event_jLatteRadioActionPerformed

    private void jSingleShotRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSingleShotRadioActionPerformed
        // TODO add your handling code here:
        coffeeSize = evt.getActionCommand().toLowerCase();
    }//GEN-LAST:event_jSingleShotRadioActionPerformed

    private void jSoftRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoftRadioActionPerformed
        // TODO add your handling code here:
        grindSize = evt.getActionCommand();
    }//GEN-LAST:event_jSoftRadioActionPerformed

    private void jRoughRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoughRadioActionPerformed
        // TODO add your handling code here:
        grindSize = evt.getActionCommand();
    }//GEN-LAST:event_jRoughRadioActionPerformed

    private void jMediumRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMediumRadioActionPerformed
        // TODO add your handling code here:
        grindSize = evt.getActionCommand();
    }//GEN-LAST:event_jMediumRadioActionPerformed

    private void jBeansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeansFieldActionPerformed
        // TODO add your handling code here:
        int beansCapacity = machine.GetBeansCapacity();
        jBeansField.setText(beansCapacity + "");
    }//GEN-LAST:event_jBeansFieldActionPerformed

    private void jGroundBeansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGroundBeansFieldActionPerformed
        // TODO add your handling code here:
        int groundBeans = machine.GetGroundPowder();
        jGroundBeansField.setText(groundBeans + "");
    }//GEN-LAST:event_jGroundBeansFieldActionPerformed

    private void jWaterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWaterFieldActionPerformed
        // TODO add your handling code here:
        int WaterCapcity = machine.GetWaterCapacity();
        jWaterField.setText(WaterCapcity + "");
    }//GEN-LAST:event_jWaterFieldActionPerformed

    private void jGrindBeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrindBeansButtonActionPerformed
        // TODO add your handling code here:
        try {
            beansToGrind = Integer.parseInt(jGrindField.getText());
            if (beansToGrind < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jGrindField.setText("");
                return;
            }
            machine.grindCoffee(beansToGrind);
            jBeansFieldActionPerformed(evt);
            jGroundBeansFieldActionPerformed(evt);
            jGrindField.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jGrindField.setText("");
        } catch (OutOfBeansException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jGrindField.setText("");
        }
    }//GEN-LAST:event_jGrindBeansButtonActionPerformed

    private void jAddBeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBeansButtonActionPerformed
        // TODO add your handling code here:
        try {
            beansToAdd = Integer.parseInt(jAddBeansField.getText());
            if (beansToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddBeansField.setText("");
                return;
            }
            machine.SetBeansCapacity(beansToAdd);
            jBeansFieldActionPerformed(evt);
            jAddBeansField.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddBeansField.setText("");
        } catch (OverFlowBenasException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddBeansField.setText("");
        }
    }//GEN-LAST:event_jAddBeansButtonActionPerformed

    private void jGrindFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrindFieldActionPerformed
        // TODO add your handling code here:;
    }//GEN-LAST:event_jGrindFieldActionPerformed

    private void jMilkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMilkFieldActionPerformed
        // TODO add your handling code here:
        int milkCapcity = machine.GetMilkCapacity();
        jMilkField.setText(milkCapcity + "");
    }//GEN-LAST:event_jMilkFieldActionPerformed

    private void jAddWaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWaterButtonActionPerformed
        // TODO add your handling code here:
        try {
            waterToAdd = Integer.parseInt(jAddWaterField.getText());
            if (waterToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddWaterField.setText("");
                return;
            }
            machine.SetWaterCapacity(waterToAdd);
            jWaterFieldActionPerformed(evt);
            jAddWaterField.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddWaterField.setText("");
        } catch (OverFlowWaterException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddWaterField.setText("");
        } catch (HeadlessException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jAddWaterButtonActionPerformed

    private void jAddMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddMilkButtonActionPerformed
        // TODO add your handling code here:
        try {
            milkToAdd = Integer.parseInt(jAddMilkField.getText());
            if (milkToAdd < 0) {
                JOptionPane.showMessageDialog(null, "The Value must be positive");
                jAddMilkField.setText("");
                return;
            }
            machine.SetMilkCapacity(milkToAdd);
            jMilkFieldActionPerformed(evt);
            jAddMilkField.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value must be integer");
            jAddMilkField.setText("");
        } catch (OverFlowMilkException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            jAddMilkField.setText("");
        }
    }//GEN-LAST:event_jAddMilkButtonActionPerformed

    private void jAddWaterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWaterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddWaterFieldActionPerformed

    private void jDeleteFromHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteFromHistoryButtonActionPerformed
        // TODO add your handling code here:
        int index = jHistoryList.getSelectedIndex();
        if (index != -1) {
            drinkList.remove(index);
            display();
        }
    }//GEN-LAST:event_jDeleteFromHistoryButtonActionPerformed

    private void jHistoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jHistoryListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jHistoryListValueChanged

    private void jWasteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWasteFieldActionPerformed
        // TODO add your handling code here:
        int wasteCapacity = machine.GetWasteCapacity();
        jWasteField.setText(wasteCapacity + "");
    }//GEN-LAST:event_jWasteFieldActionPerformed

    private void jEmptyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmptyButtonActionPerformed
        // TODO add your handling code here:
        machine.SetWaste(20);
        jWasteFieldActionPerformed(evt);
    }//GEN-LAST:event_jEmptyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jAddBeansButton;
    private javax.swing.JTextField jAddBeansField;
    private javax.swing.JButton jAddMilkButton;
    private javax.swing.JTextField jAddMilkField;
    private javax.swing.JButton jAddWaterButton;
    private javax.swing.JTextField jAddWaterField;
    private javax.swing.JRadioButton jAmericanoRadio;
    private javax.swing.JTextField jBeansField;
    private javax.swing.JButton jDeleteFromHistoryButton;
    private javax.swing.JRadioButton jDoubleShotRadio;
    private javax.swing.JButton jEmptyButton;
    private javax.swing.JRadioButton jEspressoRadio;
    private javax.swing.JButton jGrindBeansButton;
    private javax.swing.JTextField jGrindField;
    private javax.swing.JTextField jGroundBeansField;
    private javax.swing.JList<String> jHistoryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLatteRadio;
    private javax.swing.JButton jMakeButton;
    private javax.swing.JRadioButton jMediumRadio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jMilkField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRoughRadio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jSingleShotRadio;
    private javax.swing.JRadioButton jSoftRadio;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jWasteField;
    private javax.swing.JTextField jWaterField;
    // End of variables declaration//GEN-END:variables
}
